<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Views\AnimatorController\Data\ViewModels.fs" />
        <Compile Include="Views\AnimatorController\Data\Nodes.fs" />
        <Compile Include="Views\AnimatorController\Data\EventArgs.fs" />
        <Compile Include="Views\AnimatorController\Windows\Dialogs.fs" />
        <Folder Include="Views\AnimatorController\Panels\" />
        <Compile Include="Views\AnimatorController\Components\StateMachineEditor\Initialization.fs" />
        <Compile Include="Views\AnimatorController\Components\StateMachineEditor\StateMachineEditorComponent.fs" />
        <Compile Include="Views\AnimatorController\Components\ContextPanel\ContextPanelComponent.fs" />
       
        <Compile Include="Views\AnimationControllerView.fs" />
        <Folder Include="Views\AnimationLibrary\" />
        <Folder Include="Views\AnimationTesting\" />
        <Compile Include="MainWindow.axaml.fs"/>
        <Compile Include="App.axaml.fs"/>
        <Compile Include="Program.fs"/>
        
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.1" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
        <PackageReference Include="Avalonia.Themes.Simple" Version="12.1.1" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\CommonResourceFormats\src\CommonResourceFormats.AnimationFile\CommonResourceFormats.AnimationFile.fsproj" />
      <ProjectReference Include="..\..\..\FsToolbox\FsToolbox.Avalonia\FsToolbox.Avalonia.fsproj" />
      <ProjectReference Include="..\..\..\FsToolbox\FsToolbox.GameDevelopment\FsToolbox.GameDevelopment.fsproj" />
      <ProjectReference Include="..\..\..\FsToolbox\FsToolbox.GLTF\FsToolbox.GLTF.fsproj" />
      <ProjectReference Include="..\..\..\__external\nodify-avalonia\nodify-avalonia\Nodify\Nodify.csproj" />
      <ProjectReference Include="..\Anim\Anim.fsproj" />
    </ItemGroup>
</Project>
